---
accounts:

#### Example account configuration
#  - assume_role: "arn:aws:iam::123456789012:role/hostdb"
#    id:   "123456789012"
#    name: "PDXfixIT"
#    regions:
#      - "us-east-1"
#      - "us-west-1"
#    service_blacklist:
#      directconnect: true

## Please Note!
## New accounts should establish a trust relationship with `arn:aws:iam::1234567890:user/hostdb`.

  - assume_role: "arn:aws:iam::1234567890:role/hostdb"
    id: "1234567890"
    name: "Account 1"
    regions:
      - "us-east-1"
      - "us-west-1"

  - assume_role: "arn:aws:iam::0987654321:role/hostdb"
    id: "0987654321"
    name: "Account 2"
    regions:
      - "us-west-1"
      - "us-west-2"
      - "us-east-1"
      - "us-east-2"
    service_blacklist:
      directconnect: true

collector:
  debug: false
  sample_data: false
